extends: default

ignore: |
  prometheus/config/snmp.yml

rules:
  line-length:
    max: 140
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy: disable
  document-start: disable
  comments: disable
