{
 "title": "Blackbox Exporter",
 "description": "URL monitoring using Prometheus Blackbox Exporter.",
 "tags": [
  "Prometheus",
  "Web",
  "Blackbox"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   {
    "name": "instance",
    "label": "URL",
    "query": {
     "query": "label_values(probe_duration_seconds{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average availability",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(max by (instance) (probe_success){job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "URL Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(max by (instance) (probe_success){job=~\"$job\", instance=~\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "URL Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(max by (instance) (probe_success){job=~\"$job\", instance=~\"$instance\"} == 0)"
    }
   ]
  },
  {
   "title": "URL availability over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(max by (instance) (probe_success){job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Overall HTTP processing time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (phase) (probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Average processing time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(scrape_duration_seconds{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Processing time"
    }
   ]
  },
  {
   "title": "HTTP versions",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"http_version\", max by (instance, http_version) (probe_http_version){job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "HTTP/{{http_version}}"
    }
   ]
  },
  {
   "title": "TLS versions",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (version) (probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "HTTP status codes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"value\", max by (instance) (probe_http_status_code){job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max by (instance) (probe_success){job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "max by (instance) (probe_http_status_code){job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(avg by (instance) (probe_duration_seconds){job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "max by (instance, version) (probe_tls_version_info){job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "max by (instance, http_version) (probe_http_version){job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "instance" },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(max by (instance) (probe_success){job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Code HTTP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (probe_http_status_code){job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "HTTP {{ value }}"
    }
   ]
  },
  {
   "title": "TLS version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance, version) (probe_tls_version_info){job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "HTTP version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"http_version\", max by (instance, http_version) (probe_http_version){job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "HTTP/{{ http_version}}"
    }
   ]
  },
  {
   "title": "Detailed HTTP processing time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "avg by (instance, phase) (probe_http_duration_seconds){job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg by (instance) (probe_duration_seconds){job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Processing time"
    }
   ]
  }
 ]
}